name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install git+https://github.com/Platane/snk@master

      - name: Generate snake.svg
        run: snk --username ${{ github.repository_owner }} --output dist/snake.svg --palette github-dark

      - name: Push snake.svg to the output branch
        uses: actions/upload-artifact@v2
        with:
          name: snake-svg
          path: dist/snake.svg
